### ISSUE TITLE
Typo in query?

### ISSUE THREAD

**Issue by johnzzon** [ferfebles/ferfebles.github.io#1]
Hey!

Found no other way of contacting you, so here goes.

I believe there's a typo in your postgres performance blog post.

```
CREATE EXTENSION pg_trgm;
CREATE INDEX url_alias__alias_trgm_gist_idx ON url_alias USING gist (alias gist_trgm_ops);
CREATE INDEX url_alias__source_trgm_gist_idx ON url_alias USING gist (source gist_trgm_ops);
ANALIZE url_alias;
```

It should be `ANALYZE`, right?

**Comment by ferfebles** [comment]
Yes, you're right. Solved with last commit.

Thanks @Johnzzon !!
